name: music_xml
description: A Dart package project to parse MusicXML.
version: 1.0.2
homepage: https://github.com/de-men/music_xml

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  xml: ^5.3.1

dev_dependencies:
  test: ^1.16.0
